name = "lark-space"
account_id = "9d143afa60e911e9904e835bd1db8504"
compatibility_date = "2025-05-07"
preview_urls = false
main = "./worker/index.ts"

[assets]
directory = "./site/public/"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true

[env.prod]

[env.prod.route]
pattern = "lark.gay"
custom_domain = true
